### ISSUE TITLE
Revise and correct 'New X connector' titles

### ISSUE THREAD

**Issue by pmallol** [instedd/hub#100]
Found in version 0392f7b

1. Navigate to Connectors tab
2. Click on 'Add X Connector' button (i.e: Add mBuilder Connector)

Expected: the name of the connector in the title should remain the same as in the Connectors page 
(i.e: "New mBuilder connector")

**Comment by nditada** [comment]
What's the "actual"?

**Comment by pmallol** [comment]
The actual title for a mBuilder connector is "New M builder connector"

**Comment by mmuller** [comment]
Ok in Version: 1a700c0
