### ISSUE TITLE
Events from CDX cannot be used as action in Hub

### ISSUE THREAD

**Issue by mmuller** [instedd/hub#116]
Found in version: 1a700c0
CDX version  20150318.154239-9e0cf39

Preconditions:
There is a Google Spreadsheet 'Bar'
In  CDX:
There is a Laboratory 'Foo'
There is a filter where the Laboratory name is 'Foo' and Condition is 'MTB'

In Hub:
There is a Hub task where the new CDX test for the Laboratory 'Foo' are received as event and the Event properties are inserted into the Google Spreadsheet 'Bar'. In this test only 'Condition' was used as Event property.

Steps:
Go to CDX
Create a new Test in order to submit a new event
Open the Google Spreadsheet 'Bar'

Obtained:
The event properties ('Condition' in this test) was not inserted to the Google Spreadsheet (Google Spreadsheet 'Bar' in this test)

Expected:
The event properties are inserted to the Google Spreadsheet

Additional information:
I couldn't detect if CDX is exposing the event properties correctly

**Comment by nekron** [comment]
It was due to a difference between the date reported from the Quiagen device and the date used to check for new events from cdx side. See: https://github.com/instedd/cdp/commit/5cb60461f39bf09ab02903acfa92090c60f7a339
