### ISSUE TITLE
500 server error when choosing an action from Verboice connector

### ISSUE THREAD

**Issue by pmallol** [instedd/hub#130]
Found in Prod version development 

1. Navigate to tasks and create a task
2. Click on (choose) under Action
3. Select Verboice connector and Projects

Obtained: 500 server error in console

![screen shot 2015-04-15 at 9 46 39 am](https://cloud.githubusercontent.com/assets/9214460/7158875/7a6f7028-e354-11e4-9d6e-9c2ab1876ff7.png)

Poirot log: http://poirot.instedd.org/activities/0bb64cc6-2e82-1b06-d5b7-2ab912b593cb

**Comment by spalladino** [comment]
Time on Verboice server was incorrect (over 5 minutes off). Fixing it solved the issue. 
Should we consider setting up [NTP](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/set-time.html )@waj?
