### ISSUE TITLE
After Task failure any Task that use the same Connector is not executed

### ISSUE THREAD

**Issue by mmuller** [instedd/hub#131]
Found in version Development (Production environment)

Preconditions:
There is a Connector 'X'
There is a Task 'Foo' with some error (After executing this task a task failure will be obtained)
There is a Task 'Bar' configured correctly 
'Foo' and 'Bar' use the Connector 'X' as Event
 

Steps:
Execute the Event (Connector 'X') of the Task 'Foo' (A Task failure is expected)
Execute the Event (Connector 'X') of the Task 'Bar'

Obtained: 
After an error in the first Task, the second Task using the same Connector cannot be executed.
Connector cannot be used after a Task failure.

Expected:
Connector can be used after a Task failure.

**Comment by spalladino** [comment]
To clarify: the connector itself still works after a task failure, as it can receive new events. The issue is that any task that should be executed after a task that failed, is not run. The `perform` action of `NotifyJob` does not catch any exceptions.
