### ISSUE TITLE
Add version number to the footer

### ISSUE THREAD

**Issue by mmuller** [instedd/hub#134]
Found in version: Development

**Comment by matiasgarciaisaia** [comment]
@mmuller: you are referring to version `development` reported in production environment, rigth?

**Comment by mmuller** [comment]
@matiasgarciaisaia Yes, now the version number in staging environment is 511b47e. The production environment has no version number in the footer. The version number in the footer help us identify easily the current version.

**Comment by nditada** [comment]
Let's fix this in an 1.1 hotfix, please see "Repository Rules".

**Comment by romeroadrian** [comment]
Fixed in commit 4f155e49ce07c9220d551e15e5d4e2bda8ccee79
