### ISSUE TITLE
Setup environment for UNICEF flow demo

### ISSUE THREAD

**Issue by nditada** [instedd/hub#15]

**Comment by bcardiff** [comment]
The gender now is saved on the elasticsearch backend.
A kibana dashboard is attached.

![screencapture-localhost-bcardiff-kibana-3-1-2-index-html](https://cloud.githubusercontent.com/assets/459923/5705485/72b3c90a-9a58-11e4-893b-19641102d2c8.png)

source code: https://gist.github.com/bcardiff/4a373ba9a820dc983fe3
