### ISSUE TITLE
Integration between Verboice and Mbuilder is not working

### ISSUE THREAD

**Issue by mmuller** [instedd/hub#50]
Having a Task where the Event is a finished Verboice call and the Action is an External Trigger excution:
1. Execute a Verboice call

After the call is finished the External Trigger is not executed.   

![screen shot 2014-12-09 at 4 08 46 pm](https://cloud.githubusercontent.com/assets/518152/5363833/bfcb469c-7fbd-11e4-9369-a2343b1dd435.png)

**Comment by pmallol** [comment]
Ok in v. 0a41dab
