### ISSUE TITLE
RapidPro response is stored as 'null' in ElasticSearch

### ISSUE THREAD

**Issue by mmuller** [instedd/hub#55]
Found in version 2c70408

Having a Task where the Event is a survey Update from RapidPro Connector and the Action is an Patient Update to 'hub_unicef' in ElasticSearch:

Run a survey
Send Response with 'No' in order to set the variable 'Fever' (string) as 'No'
Send a request to ElasticSearch to get the Patient Update

Obtained: 
ElasticSearch returns the following object where 'fever' is 'null'

hits: [
{
_index: "hub_unicef",
_type: "patients",
_id: "ByB8zl9HR8aqm-NqQPCNrQ",
_score: 1,
_source: {
fever: null,
name: "QA Test",
phone: "+541135644146"
}
}
]

![screen shot 2014-12-11 at 3 13 47 pm](https://cloud.githubusercontent.com/assets/518152/5399284/6ac06e52-8148-11e4-9cc1-ba9438e46624.png)

![screen shot 2014-12-11 at 3 22 01 pm](https://cloud.githubusercontent.com/assets/518152/5399417/dca74fc6-8149-11e4-8fd0-dd10cd79f458.png)

**Comment by chadad** [comment]
It seems to be working ok now. I tried this same example and the result is:
 "hits" : {
    "total" : 1,
    "max_score" : 1.0,
    "hits" : [ {
      "_index" : "hub_unicef",
      "_type" : "patients",
      "_id" : "wsc64GuEQzyYnGuLs5cVXA",
      "_score" : 1.0,
      "_source":{"fever":"No","phone":"+541156309961"}
    } ]
  }


Please check again and let me know if still happens!

**Comment by pmallol** [comment]
Working ok in version 0a41dab
