### ISSUE TITLE
GoogleSpreadsheet cannot be updated through the Hub

### ISSUE THREAD

**Issue by mmuller** [instedd/hub#70]
Found in Version: ccff7a1

Given the following objects: 
A Verboice Project 'Foo' where there is a variable 'took_temperature'
A Google Spreadsheet with the columns 'address' and 'took_temperature'. For the address '1234' the value of 'took_temperature' is '3'.
A Google Spreadsheet Connector
A Verboice Connector
A Task where 'address' and 'toook_temperature' from the Events are stored as 'address' and 'took_temperature' in the Actions 

Steps:
Execute a Verboice call for the Project 'Foo'
Store the value '1' for 'took_temperature' 
Hang up the call
Open the Google Spreadsheet

Obtained:
The value of 'took_temperature' is '3'. It didn't change.

Expected: 
The value of 'took_temperature' is '1'. The variable should be updated

![screen shot 2014-12-17 at 4 33 17 pm](https://cloud.githubusercontent.com/assets/518152/5478004/261cb0fa-860f-11e4-9233-220f9f3804d5.png)

**Comment by pmallol** [comment]
@asterite: the GoogleSpreadsheet is updated successfully through hub but now the problem is that the update also inserts a new row. (issue #87)
