### ISSUE TITLE
When creating a Task, Event and Action labels are not used from reflect response

### ISSUE THREAD

**Issue by asterite** [instedd/hub#77]
For example Verboice's Call action has the following reflect:

```json
{
  "label": "Call",
  "args": {
    "channel": {
      "type": "string",
      "label": "Channel"
    },
    "number": {
      "type": "string",
      "label": "Number"
    },
    "vars": {
      "type": {
        "kind": "struct",
        "members": {
          "age": {
            "type": "string"
          }
        },
        "open": true
      }
    }
  }
}
```

But the UI shows:

```
- channel: ___
- number: ___
- vars:
  - age: ___
```

It should show:

```
- Channel: ___
- Number: ___
- vars:
  - age: ___
```

This is not very important if the label is a capitalized version of the name, but sometimes there's a mapping from internal code to external labels and the user should see the external ones.

**Comment by bcardiff** [comment]
The more complex solution was to to make the hub use ruby-hub_client gem. But doing that would force to change how task are saved in order to persist a copy of the reflect. Changing how open structs are stored. Yet, this change will facilitate #45 and in the future #81
