### ISSUE TITLE
Label changes to id when dropping a pill in 'ACT>cased confirmed sick' as the action

### ISSUE THREAD

**Issue by pmallol** [instedd/hub#98]
Found in version 0392f7b

Preconditions:
User has an ACT connector

1. Create a task 
2. As the Event select "Finished call" after selecting a call flow from Verboice's connector
3. As the Action select "Update" after Cases in the ACT connector
4. Drag and drop a pill into a text field from the action

Obtained: the label was replaced by the id. (e.i: label "Case ID" is replaced by "case_id")
Expected: the label should remain the same

**Comment by mmuller** [comment]
Ok in Version: 1a700c0
