### ISSUE TITLE
Replace 'trigger' with 'connector' in title

### ISSUE THREAD

**Issue by pmallol** [instedd/hub#99]
Found in version 0392f7b

1. Navigate to Connectors
2. Create a connector with [name]
3. Open connector [name]

Obtained: the description title is "Edit '[name]' trigger"

**Comment by ggiraldez** [comment]
Fixed in 37002a714e7778c3299493e21bc327558bb14fc1

**Comment by mmuller** [comment]
Ok in Version: 1a700c0
